config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'mainpage#index'

  get 'clinics/search', to: 'clinics#search', as: 'clinics_search'
  get 'clinics/download_csv', to: 'clinics#download_csv', as: 'clinics_download_csv'
  get 'clinics/download_pdf', to: 'clinics#download_pdf', as: 'clinics_download_pdf'
  get 'clinics/:id/download_pdf/', to: 'clinics#download_pdf_with_id', as: 'clinics_download_pdf_with_id'
  get 'users/download_pdf/', to: 'mainpage#download_pdf', as: 'users_download_pdf'
  get 'clinics/:id/searchshow', to: 'clinics#searchshow', as: 'clinics_search_show'
  get 'departments/search', to: 'departments#search', as: 'departments_search'
  get 'doctors/search', to: 'doctors#search', as: 'doctors_search'
  get 'specialties/search', to: 'specialties#search', as: 'specialties_search'
  get 'patient_cards/search', to: 'patient_cards#search', as: 'patient_cards_search'
  get 'patients/search', to: 'patients#search', as: 'patients_search'
  
  root 'mainpage#index'

  devise_for :users, controllers: { registrations: "users/registrations" }
  
  resources :clinics do
    resources :departments
  end
  
  resources :departments do
    resources :doctors
  end
  
  resources :departments do
    resources :patient_cards
  end
  
  resources :patient_cards

  resources :patients
  
  resources :doctors do
    resources :specialties
  end
  
  resources :specialties
end

app/models/clinic.rb
class Clinic < ApplicationRecord
	has_many :departments, dependent: :destroy
	has_many :doctors, through: :departments
	has_many :patient_cards, dependent: :destroy
	has_many :patients, through: :patient_cards

	validates :name, presence: true, length: { maximum: 100 }
	validates :email, presence: true, length: { maximum: 255 }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Incorrect email format!" }
	validates :phone, presence: true, length: { maximum: 20 }, format: { with: /\A\+?\d+\z/, message: "Incorrect phone format!" }
	validates :address, presence: true, length: { maximum: 100 }
    validates :year_of_establishment, presence: true, length: { maximum: 10 }, format: { with: /\A(16[0-9]{2}|17[0-9]{2}|18[0-9]{2}|19[0-9]{2}|20[0-1][0-9]|202[0-3])\z/, message: "Incorrect year of establishment format!" }
	validates :facility_type, presence: true, length: { maximum: 100 }
	validates :city, presence: true, length: { maximum: 100 }
	validates :rating_mortality, presence: true, length: { maximum: 100 }
	
	def update_name(new_name)
		self.name = new_name
		save
	end

	def update_email(new_email)
		self.email = new_email
		save
	end

	def update_phone(new_phone)
		self.phone = new_phone
		save
	end

	def update_address(new_address)
		self.address = new_address
		save
	end

	def update_year_of_establishment(new_year_of_establishment)
		self.year_of_establishment = new_year_of_establishment
		save
	end

	def update_facility_type(new_facility_type)
		self.facility_type = new_facility_type
		save
	end

	def update_city(new_city)
		self.city = new_city
		save
	end

	def update_rating_mortality(new_rating_mortality)
		self.rating_mortality = new_rating_mortality
		save
	end
end

app/controllers/clinics_controller.rb
require 'csv'
require 'prawn'
require 'prawn/table'
require 'thread'

class ClinicsController < ApplicationController

  def index
    clinics = Clinic.all

    if params[:sort].present?
      clinics = case params[:sort]
      when "id"
        clinics.order!(id: params[:direction])
      when "departments_count"
        clinics.left_outer_joins(:departments)
               .group(:id)
               .order!("COUNT(departments.id) #{params[:direction] == 'desc' ? 'DESC' : 'ASC'}")
      when "doctors_count"
        clinics.left_outer_joins(:doctors)
               .group(:id)
               .order!("COUNT(doctors.id) #{params[:direction] == 'desc' ? 'DESC' : 'ASC'}")
      when "name"
        clinics.order!(name: params[:direction])
      when "facility_type"
        clinics.order!(facility_type: params[:direction])
      when "city"
        clinics.order!(city: params[:direction])
      when "rating_mortality"
        clinics.order!(rating_mortality: params[:direction])
      end
    end

    @clinics = ClinicQuery.new(clinics.page(params[:page]).per(10))
    @clinics = @clinics.search(:name, params[:name]) if params[:name].present?
    @clinics = @clinics.result
  end
  
  def search
    clinics = Clinic.all

    if params[:sort].present?
      clinics = case params[:sort]
      when "id"
        clinics.order!(id: params[:direction])
      when "departments_count"
        clinics.left_outer_joins(:departments)
               .group(:id)
               .order!("COUNT(departments.id) #{params[:direction] == 'desc' ? 'DESC' : 'ASC'}")
      when "doctors_count"
        clinics.left_outer_joins(:doctors)
               .group(:id)
               .order!("COUNT(doctors.id) #{params[:direction] == 'desc' ? 'DESC' : 'ASC'}")
      when "name"
        clinics.order!(name: params[:direction])
      when "facility_type"
        clinics.order!(facility_type: params[:direction])
      when "city"
        clinics.order!(city: params[:direction])
      when "rating_mortality"
        clinics.order!(rating_mortality: params[:direction])
      end
    end

    @clinics = ClinicQuery.new(clinics.page(params[:page]).per(10))
    @clinics = @clinics.search(:name, params[:name]) if params[:name].present?
    @clinics = @clinics.result

    render :index
  end
  
  def show
    @clinic = Clinic.find(params[:id])
    patients = @clinic.patients.page(params[:page]).per(10)

    if params[:sort].present?
      patients = case params[:sort]
      when "id"
        patients.order(id: params[:direction])
      when "name"
        patients.order(name: params[:direction])
      when "birthdate"
        patients.order(birthdate: params[:direction])
      when "phone"
        patients.order(phone: params[:direction])
      else
        patients
      end
    end

    @patients = PatientQuery.new(patients)
    @patients = @patients.search(:name, params[:name]) if params[:name].present?
    @patients = @patients.search(:age, params[:age]) if params[:age].present?
    @patients = @patients.search(:phone, params[:phone]) if params[:phone].present?
    @patients = @patients.sort(params[:sort], params[:direction]) if params[:sort].present?
    @patients = @patients.result

    @patientcards = PatientCard.where(patient_id: @patients.map(&:id)).index_by(&:patient_id)
  end

  def searchshow
    @clinic = Clinic.find(params[:id])
    @patients = PatientQuery.new(@clinic.patients.page(params[:page]).per(10))
    @patients = @patients.search(:name, params[:name]) if params[:name].present?
    @patients = @patients.search(:age, params[:age]) if params[:age].present?
    @patients = @patients.search(:phone, params[:phone]) if params[:phone].present?
    @patients = @patients.sort(params[:sort], params[:direction]) if params[:sort].present?
    @patients = @patients.result

    @patientcards = PatientCard.where(clinic_id: @clinic.id, patient_id: @patients.pluck(:id)).index_by(&:patient_id)

    render :show
  end

  def download_csv
    mutex = Mutex.new
    threads = []
    filename = "All_clinics_and_patients.csv"

    csv_headers = ["Clinic Name", "Clinic Email", "Clinic Phone", "Clinic Address", "Year of Establishment", "Facility Type", "City", "Rating (Mortality)", "Department Count", "Doctor Count", "Patient Name", "Patient Email", "Patient Phone", "Patient Address", "Patient Birthdate"]

    Tempfile.open(filename) do |tempfile|
      CSV.open(tempfile, "wb") do |csv|
        csv << csv_headers

        Clinic.includes(:patients).find_each do |clinic|
          clinic_data = [
            clinic.name,
            clinic.email,
            clinic.phone,
            clinic.address,
            clinic.year_of_establishment,
            clinic.facility_type,
            clinic.city,
            clinic.rating_mortality,
            clinic.departments.count,
            clinic.doctors.count
          ]
          csv << clinic_data

          clinic.patients.each_with_index do |patient, index|
            patient_data = [
              patient.name,
              patient.email,
              patient.phone,
              patient.address,
              patient.birthdate
            ]
            csv << patient_data
          end
        end
      end

      threads << Thread.new do
        mutex.synchronize do
          send_file tempfile.path, filename: filename, type: "application/csv"
        end
      end

      threads.each(&:join)
    end
  end

  def download_pdf
    mutex = Mutex.new
    threads = []
    filename = "All_clinics_and_patients.pdf"

    Tempfile.open(filename) do |tempfile|
      Prawn::Document.generate(tempfile.path) do |pdf|
        pdf.font_families.update("Georgia" => {
          normal: "#{Rails.root}/app/assets/fonts/NotoSansGeorgian-Regular.ttf",
          bold: "#{Rails.root}/app/assets/fonts/NotoSansGeorgian-Bold.ttf"
        })
        pdf.font "Georgia"

        clinics = Clinic.includes(:patients)

        clinics.each_with_index do |clinic, index|
          pdf.move_down(10)
          pdf.text "Clinic #{index + 1} Information", size: 14, style: :bold, align: :center

          clinic_data = [
            [{ content: 'Info', font_style: :bold }, { content: '', image: "#{Rails.root}/app/assets/images/clinic_info.png", fit: [20, 20] }],
            ["Clinic name", clinic.name],
            ["Email", clinic.email],
            ["Phone", clinic.phone],
            ["Address", clinic.address],
            ["Year of Establishment", clinic.year_of_establishment],
            ["Type", clinic.facility_type],
            ["City", clinic.city],
            ["Rating (Mortality)", clinic.rating_mortality],
            ["Number of departments", clinic.departments.count],
            ["Number of doctors", clinic.doctors.count]
          ]

          pdf.table(clinic_data, width: 400, cell_style: { borders: [], padding: [4, 2] })

          if clinic.patients.any?
            pdf.move_down(10)
            pdf.text "Patients", size: 14, style: :bold, align: :center

            patient_headers = [
              { content: "Info", width: 30 },
              { content: "Name", width: 80 },
              { content: "Birth", width: 37 },
              { content: "Email", width: 95 },
              { content: "Phone", width: 55 },
              { content: "Address", width: 105 },
              { content: "Code", width: 55 },
              { content: "Doctor", width: 93 }
            ]

            patient_data = clinic.patients.map do |patient|
              [
                { content: '', image: "#{Rails.root}/app/assets/images/patient_info.png", fit: [20, 20] },
                patient.name,
                patient.birthdate,
                patient.email,
                patient.phone,
                patient.address,
                patient.patient_card&.code,
                patient.patient_card&.doctor&.name
              ]
            end

            pdf.table([patient_headers] + patient_data, width: 550, cell_style: { borders: [], padding: [4, 2] })
          end

          pdf.start_new_page if index < clinics.size - 1
        end
      end

      threads << Thread.new do
        mutex.synchronize do
          send_file tempfile.path, filename: filename, type: "application/pdf"
        end
      end

      threads.each(&:join)
    end
  end

  def download_pdf_with_id
    mutex = Mutex.new
    threads = []
    
    clinic = Clinic.find(params[:id])
    filename = "#{clinic.name}_and_patients.pdf".gsub(' ', '_')
    
    threads << Thread.new do
      Prawn::Document.generate(filename) do |pdf|
        pdf.font_families.update("Georgia" => {
          normal: "#{Rails.root}/app/assets/fonts/NotoSansGeorgian-Regular.ttf",
          bold: "#{Rails.root}/app/assets/fonts/NotoSansGeorgian-Bold.ttf"
        })
        pdf.font "Georgia"
    
        pdf.move_down(10)
        pdf.text "Clinic Information", size: 14, style: :bold, align: :center
    
        clinic_data = [
          [{ content: 'Info', font_style: :bold }, { content: '', image: "#{Rails.root}/app/assets/images/clinic_info.png", fit: [20, 20] }],
          ["Clinic name", clinic.name],
          ["Email", clinic.email],
          ["Phone", clinic.phone],
          ["Address", clinic.address],
          ["Year of Establishment", clinic.year_of_establishment],
          ["Type", clinic.facility_type],
          ["City", clinic.city],
          ["Rating (Mortality)", clinic.rating_mortality],
          ["Number of departments", clinic.departments.count],
          ["Number of doctors", clinic.doctors.count]
        ]
    
        pdf.table(clinic_data, width: 400, cell_style: { borders: [], padding: [4, 2] })
    
        if clinic.patients.any?
          pdf.move_down(10)
          pdf.text "Patients", size: 14, style: :bold, align: :center
    
          patient_headers = [
            { content: "Info", width: 30 },
            { content: "Name", width: 80 },
            { content: "Birth", width: 37 },
            { content: "Email", width: 95 },

app/helpers/clinics_helper.rb
module ClinicsHelper
  def calculate_age(birthdate)
    now = Time.now.utc.to_date
    age = now.year - birthdate.year
    age -= 1 if now.month < birthdate.month || (now.month == birthdate.month && now.day < birthdate.day)
    age
  end
end

app/views/clinics/edit.html.erb
<%= stylesheet_link_tag 'change' %>

<h1>Edit Clinic</h1>

<%= form_for @clinic, data: { turbo: false } do |f| %>
  <div>
    <%= f.label :name, class: "label" %>
    <%= f.text_field :name, class: "input-field inline", placeholder: "Clinic name" %><br>
  </div>

  <div>
    <%= f.label :email, class: "label" %>
    <%= f.text_field :email, class: "input-field inline", placeholder: "example@gmail.com" %><br>
  </div>
  
  <div>
    <%= f.label :phone, class: "label" %>
    <%= f.text_field :phone, class: "input-field inline", placeholder: "+3801234567" %><br>
  </div>
  
  <div>
    <%= f.label :address, class: "label" %>
    <%= f.text_field :address, class: "input-field inline", placeholder: "123 Adr st" %><br>
  </div>

  <div>
    <%= f.label :year_of_establishment, class: "label" %>
    <%= f.text_field :year_of_establishment, class: "input-field inline", placeholder: "1600-2023" %><br>
  </div>

  <div>
    <%= f.label :facility_type, class: "label" %>
    <%= f.text_field :facility_type, class: "input-field inline", placeholder: "Clinic type" %><br>
  </div>

  <div>
    <%= f.label :city, class: "label" %>
    <%= f.text_field :city, class: "input-field inline", placeholder: "c. Zubrowka" %><br>
  </div>

  <div>
    <%= f.label :rating_mortality, class: "label" %>
    <%= f.text_field :rating_mortality, class: "input-field inline", placeholder: "1-5" %><br>
  </div>

  <%= f.submit "Update", class: "button" %><br>

  <div id="error-message" class="large-label"></div>
<% end %>

app/views/clinics/index.html.erb
<%= stylesheet_link_tag 'view' %>

<h1>View clinics</h1>

<table>
  <thead>
    <tr>
      <th style="width: 55px;">
        <%= label_tag "id", "ID" %>
        <%= link_to params[:sort] == "id" && params[:direction] == "asc" ? "▼" : "▲", { sort: "id", direction: (params[:sort] == "id" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility_type: params[:facility_type], city: params[:city], rating_mortality: params[:rating_mortality] }, class: "sort-icon #{params[:sort] == "id" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 220px;">
        <%= form_tag(clinics_search_path, method: "get") do %>
          <%= label_tag "name", "Name" %>
          <%= text_field_tag "name", params[:name], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "name" && params[:direction] == "asc" ? "▼" : "▲", { sort: "name", direction: (params[:sort] == "name" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility_type: params[:facility_type], city: params[:city], rating_mortality: params[:rating_mortality] }, class: "sort-icon #{params[:sort] == "name" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th style="min-width: 120px; width: auto;">
        <%= label_tag "departments_count", "Number of departments" %>
        <%= link_to params[:sort] == "departments_count" && params[:direction] == "asc" ? "▼" : "▲", { sort: "departments_count", direction: (params[:sort] == "departments_count" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility_type: params[:facility_type], city: params[:city], rating_mortality: params[:rating_mortality] }, class: "sort-icon #{params[:sort] == "departments_count" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="min-width: 120px; width: auto;">
        <%= label_tag "doctors_count", "Number of doctors" %>
        <%= link_to params[:sort] == "doctors_count" && params[:direction] == "asc" ? "▼" : "▲", { sort: "doctors_count", direction: (params[:sort] == "doctors_count" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility_type: params[:facility_type], city: params[:city], rating_mortality: params[:rating_mortality] }, class: "sort-icon #{params[:sort] == "doctors_count" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 120px;">
        <%= label_tag "facility_type", "Clinic Type" %>
        <%= link_to params[:sort] == "facility_type" && params[:direction] == "asc" ? "▼" : "▲", { sort: "facility_type", direction: (params[:sort] == "facility_type" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility_type: params[:facility_type], city: params[:city], rating_mortality: params[:rating_mortality] }, class: "sort-icon #{params[:sort] == "facility_type" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 105px;">
        <%= label_tag "city", "City" %>
        <%= link_to params[:sort] == "city" && params[:direction] == "asc" ? "▼" : "▲", { sort: "city", direction: (params[:sort] == "city" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility_type: params[:facility_type], city: params[:city], rating_mortality: params[:rating_mortality] }, class: "sort-icon #{params[:sort] == "city" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 120px;">
        <%= label_tag "rating_mortality", "Mortality rating" %>
        <%= link_to params[:sort] == "rating_mortality" && params[:direction] == "asc" ? "▼" : "▲", { sort: "rating_mortality", direction: (params[:sort] == "rating_mortality" && params[:direction] == "asc") ? "desc" : "asc", name: params[:name], departments_count: params[:departments_count], doctors_count: params[:doctors_count], facility_type: params[:facility_type], city: params[:city], rating_mortality: params[:rating_mortality] }, class: "sort-icon #{params[:sort] == "rating_mortality" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th colspan="3" style="width: 270px;">Data interraction</th>
    </tr>
  </thead>
  <tbody>
    <% @clinics.each do |clinic| %>
      <tr>
        <td><%= clinic.id %></td>
        <td><%= clinic.name %></td>
        <td><%= clinic.departments.count %></td>
        <td><%= clinic.doctors.count %></td>
        <td><%= clinic.facility_type %></td>
        <td><%= clinic.city %></td>
        <td><%= clinic.rating_mortality %></td>
        <td><%= link_to 'Show', clinic_path(clinic), class: "button" %></td>
        <td><%= link_to 'Edit', edit_clinic_path(clinic), class: "button" %></td>
        <td><%= button_to 'Delete', clinic_path(clinic), method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @clinics %>

<div class="links-container">
  <%= link_to 'Clinics and patients (CSV)', clinics_download_csv_path, class: "bottom-button" %>
  <%= link_to 'Clinics and patients (PDF)', clinics_download_pdf_path, class: "bottom-button" %>
  <%= link_to 'New Clinic', new_clinic_path, class: "bottom-button" %>
  <%= link_to 'Main page', '/', class: "bottom-button" %>
</div>

app/views/clinics/new.html.erb
<%= stylesheet_link_tag 'change' %>

<h1>New Clinic</h1>

<%= form_for @clinic do |f| %>
  <%= f.label :name, class: "label" %>
  <%= f.text_field :name, class: "input-field", placeholder: "Clinic name" %><br>

  <%= f.label :email, class: "label" %>
  <%= f.text_field :email, class: "input-field", placeholder: "example@gmail.com" %><br>

  <%= f.label :phone, class: "label" %>
  <%= f.text_field :phone, class: "input-field", placeholder: "+3801234567" %><br>

  <%= f.label :address, class: "label" %>
  <%= f.text_field :address, class: "input-field", placeholder: "123 Adr st" %><br>

  <%= f.label :year_of_establishment, class: "label" %>
  <%= f.text_field :year_of_establishment, class: "input-field", placeholder: "1600-2023" %><br>

  <%= f.label :facility_type, class: "label" %>
  <%= f.text_field :facility_type, class: "input-field", placeholder: "Clinic type" %><br>

  <%= f.label :city, class: "label" %>
  <%= f.text_field :city, class: "input-field", placeholder: "c. Zubrowka" %><br>

  <%= f.label :rating_mortality, class: "label" %>
  <%= f.text_field :rating_mortality, class: "input-field", placeholder: "Describe impression" %><br>

  <%= f.submit "Create", class: "button" %>

  <div id="error-message" class="large-label"></div>
<% end %>

app/views/clinics/show.html.erb
<%= stylesheet_link_tag 'view' %>

<h1>Clinic info</h1>

<table>
  <thead>
    <tr>
      <th style="width: 120px;">
        <%= label_tag "id", "Patient ID" %>
        <%= link_to params[:sort] == "id" && params[:direction] == "asc" ? "▼" : "▲", { sort: "id", direction: (params[:sort] == "id" && params[:direction] == "asc") ? "desc" : "asc" }, class: "sort-icon #{params[:sort] == "id" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
      </th>
      <th style="width: 220px;">
        <%= form_tag(clinics_search_show_path(@clinic.id), method: "get") do %>
          <%= label_tag "name", "Name" %>
          <%= text_field_tag "name", params[:name], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "name" && params[:direction] == "asc" ? "▼" : "▲", { sort: "name", direction: (params[:sort] == "name" && params[:direction] == "asc") ? "desc" : "asc" }, class: "sort-icon #{params[:sort] == "name" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th style="width: 280px;">
        <%= form_tag(clinics_search_show_path(@clinic.id), method: "get") do %>
          <%= label_tag "age", "Patient Age" %>
          <%= text_field_tag "age", params[:age], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "birthdate" && params[:direction] == "asc" ? "▼" : "▲", { sort: "birthdate", direction: (params[:sort] == "birthdate" && params[:direction] == "asc") ? "desc" : "asc" }, class: "sort-icon #{params[:sort] == "birthdate" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th style="width: 90px;">
        <%= label_tag "card_code", "Card Code" %>
      </th>
      <th style="width: 240px;">
        <%= form_tag(clinics_search_show_path(@clinic.id), method: "get") do %>
          <%= label_tag "phone", "Phone" %>
          <%= text_field_tag "phone", params[:phone], placeholder: "Search...", size: 4 %>
          <%= submit_tag "Search", class: "small-button" %>
          <%= link_to params[:sort] == "phone" && params[:direction] == "asc" ? "▼" : "▲", { sort: "phone", direction: (params[:sort] == "phone" && params[:direction] == "asc") ? "desc" : "asc" }, class: "sort-icon #{params[:sort] == "phone" ? (params[:direction] == "asc" ? "asc" : "desc") : ""}" %>
        <% end %>
      </th>
      <th colspan="2">Data interaction</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.id %></td>
        <td><%= patient.name %></td>
        <td><%= calculate_age(patient.birthdate) %></td>
        <td><%= @patientcards[patient.id].code %></td>
        <td><%= patient.phone %></td>
        <td>
          <%= link_to Doctor.find_by(id: @patientcards[patient.id]&.doctor_id)&.name, doctor_path(@patientcards[patient.id]&.doctor_id), class: "button" if @patientcards[patient.id] %>
        </td>
        <td><%= link_to "Show", patient_path(patient), class: "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @patients %>

<div class="links-container">
  <%= link_to 'Clinic info (PDF)', clinics_download_pdf_with_id_path, class: "bottom-button" %>
  <%= link_to 'Back to clinics', clinics_path, class: "bottom-button" %>
  <%= link_to 'Main page', '/', class: "bottom-button" %>
</div>